# Generated by Django 4.1.5 on 2023-01-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_contact_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_user',
        ),
    ]
