# Generated by Django 4.1.5 on 2023-01-06 22:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0009_contact_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
